name = "aafu"
license = "MIT"
licenselink = "https://github.com/darshanbaral/aafu/blob/master/LICENSE"
description = "Single page CV theme based on https://github.com/darshanbaral/aafu"
homepage = "https://github.com/frohlichcortezh/aafu"
tags = ["CV", "single page", "resume"]
features = ["responsive", "clean", "minimalist"]
min_version = "0.41"

[author]
  name = "Hector Frohlich Cortez"
  homepage = "https://www.frohlichcortezh.github.com/"
